---
packageName: kubernetes
faults:
  - name: pod-delete
    CSV: pod-delete.chartserviceversion.yaml
    desc: "pod-delete"
  - name: container-kill
    CSV: container-kill.chartserviceversion.yaml
    desc: "container-kill"
  - name: docker-service-kill
    CSV: docker-service-kill/docker-service-kill.chartserviceversion.yaml
    desc: "docker-service-kill"
