apiVersion: v1
kind: LimitRange
metadata:
  name: litmus-exp-container-memory-policy
  namespace: litmus-exp
spec:
  limits:
  - type: Container
    max:
      memory: 10Gi
    min:
      memory: 128Mi
    default:
      memory: 1Gi
    defaultRequest:
      memory: 256Mi
    maxLimitRequestRatio:
      memory: "40"
