$env:VERSION = "3.0.0"
$env:INFRA_DEPLOYMENTS = "false"
$env:DB_SERVER = "mongodb://localhost:27017"
$env:JWT_SECRET = "litmus-portal@123"
$env:DB_USER = "admin"
$env:DB_PASSWORD = "1234"
$env:SELF_AGENT = "false"
$env:INFRA_COMPATIBLE_VERSIONS = '["3.0.0"]'
$env:ALLOWED_ORIGINS = '^(http://|https://|)(localhost|host\.docker\.internal)(:[0-9]+|)'
$env:SKIP_SSL_VERIFY = "true"
$env:ENABLE_GQL_INTROSPECTION = "true"
$env:INFRA_SCOPE = "cluster"
$env:SUBSCRIBER_IMAGE = "litmuschaos/litmusportal-subscriber:3.0.0"
$env:EVENT_TRACKER_IMAGE = "litmuschaos/litmusportal-event-tracker:3.0.0"
$env:ARGO_WORKFLOW_CONTROLLER_IMAGE = "litmuschaos/workflow-controller:v3.3.1"
$env:ARGO_WORKFLOW_EXECUTOR_IMAGE = "litmuschaos/argoexec:v3.3.1"
$env:LITMUS_CHAOS_OPERATOR_IMAGE = "litmuschaos/chaos-operator:3.0.0"
$env:LITMUS_CHAOS_RUNNER_IMAGE = "litmuschaos/chaos-runner:3.0.0"
$env:LITMUS_CHAOS_EXPORTER_IMAGE = "litmuschaos/chaos-exporter:3.0.0"
$env:CONTAINER_RUNTIME_EXECUTOR = "k8sapi"
$env:WORKFLOW_HELPER_IMAGE_VERSION = "3.0.0"
$env:DEFAULT_HUB_GIT_URL = "https://github.com/sharmadeep2/chaos-charts"
$env:DEFAULT_HUB_BRANCH_NAME = "master"
$env:LITMUS_AUTH_GRPC_ENDPOINT = "localhost"
$env:LITMUS_AUTH_GRPC_PORT = "3030"
cd "c:\Users\sharmadeep\AgentCert\chaoscenter\graphql\server"
.\server.exe
