---
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: pod-container-kill-chaos
  namespace: default
spec:
  appinfo:
    appns: ''
    applabel: ''
    appkind: ''
  # It can be active/stop
  engineState: 'active'
  chaosServiceAccount: pod-container-kill-sa
  experiments:
    - name: pod-container-kill
      spec:
        components:
          env:
            # set chaos duration (in sec) as desired
            - name: TOTAL_CHAOS_DURATION
              value: '30'

            # Container name to target
            - name: CONTAINER_NAME
              value: ''

            # Chaos interval
            - name: CHAOS_INTERVAL
              value: '10'

            ## percentage of total pods to target
            - name: PODS_AFFECTED_PERC
              value: ''
