---
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: network-latency-chaos
  namespace: default
spec:
  appinfo:
    appns: ''
    applabel: ''
    appkind: ''
  # It can be active/stop
  engineState: 'active'
  chaosServiceAccount: network-latency-sa
  experiments:
    - name: network-latency
      spec:
        components:
          env:
            # set chaos duration (in sec) as desired
            - name: TOTAL_CHAOS_DURATION
              value: '60'

            # set latency (in ms) as desired
            - name: NETWORK_LATENCY
              value: '100'

            # set jitter (in ms) as desired
            - name: JITTER
              value: '0'

            # Network interface to use
            - name: NETWORK_INTERFACE
              value: 'eth0'

            # Destination network to target
            - name: DESTINATION_NETWORK
              value: ''

            # Source port (optional)
            - name: SOURCE_PORT
              value: ''

            # Destination port (optional)
            - name: DESTINATION_PORT
              value: ''

            ## percentage of total pods to target
            - name: PODS_AFFECTED_PERC
              value: ''

            # Protocol to target
            - name: PROTOCOL
              value: 'tcp'

