---
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: network-policy-misconfig-chaos
  namespace: default
spec:
  appinfo:
    appns: ''
    applabel: ''
    appkind: ''
  # It can be active/stop
  engineState: 'active'
  chaosServiceAccount: network-policy-misconfig-sa
  experiments:
    - name: network-policy-misconfig
      spec:
        components:
          env:
            # set chaos duration (in sec) as desired
            - name: TOTAL_CHAOS_DURATION
              value: '60'

            # Policy action to apply
            - name: POLICY_ACTION
              value: 'allow'

            ## percentage of total pods to target
            - name: PODS_AFFECTED_PERC
              value: ''
