---
apiVersion: litmuschaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  name: node-resource-hog
  version: 0.1.0
  annotations:
    categories: Kubernetes
    vendor: LitmusChaos
spec:
  displayName: Node Resource Hog
  categoryDescription: |
    Node-Resource-Hog fault exhausts resources on specific Kubernetes nodes.
    - Causes CPU and memory resource consumption on specific nodes using cgroups and litmus nsutil which consume node resources.
    - It can test the cluster's resilience to resource starvation and potential pod evictions due to resource exhaustion.
    - Node should recover once chaos is stopped. Expectation is that workloads should be rescheduled and running despite chaos.
  keywords:
    - Kubernetes
    - Node
    - Resource
    - CPU
    - Memory
  platforms:
    - GKE
    - Packet(Kubeadm)
    - Minikube
    - EKS
    - AKS
    - Kind
    - Rancher
    - OpenShift(OKD)
  maintainers:
    - name: ksatchit
      email: karthik.s@harness.io
    - name: Udit Gaurav
      email: udit.gaurav@harness.io
  experiments:
    - node-resource-hog
    - sock-shop
    - sock-shop-promProbe
  minKubeVersion: 1.12.0
  labels:
    app.kubernetes.io/component: chartserviceversion
    app.kubernetes.io/version: ci
  links:
    - name: Documentation
      url: https://litmuschaos.github.io/litmus/experiments/categories/contents
  icon:
    - url:
      mediatype: ""
