package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"os"
	"strings"
	"time"

	"github.com/google/uuid"
	"github.com/litmuschaos/litmus/chaoscenter/graphql/server/graph/model"
	"github.com/litmuschaos/litmus/chaoscenter/graphql/server/pkg/agent_registry"
	"github.com/litmuschaos/litmus/chaoscenter/graphql/server/pkg/model_library"
	"github.com/litmuschaos/litmus/chaoscenter/graphql/server/utils"
)

// RegisterAgent is the resolver for the registerAgent field.
func (r *mutationResolver) RegisterAgent(ctx context.Context, input model.RegisterAgentInput) (*model.RegisterAgentResponse, error) {
	// Convert GraphQL input to service request
	req, err := agent_registry.MapRegisterAgentInputToRequest(input)
	if err != nil {
		return nil, err
	}

	// Call service layer
	agent, err := r.agentRegistryService.RegisterAgent(ctx, req)
	if err != nil {
		return nil, err
	}

	// Convert service response to GraphQL model
	agentModel := agent_registry.MapAgentToModel(agent)
	return &model.RegisterAgentResponse{
		Agent:              agentModel,
		LangfuseSyncStatus: model.SyncStatusSkipped,
	}, nil
}

// ValidateHelmDeployment is the resolver for the validateHelmDeployment field.
func (r *mutationResolver) ValidateHelmDeployment(ctx context.Context, projectID string, request model.DeployAgentWithHelmRequest) (*model.HelmValidationResponse, error) {
	version := "v1.0.0"
	if request.Version != nil {
		version = *request.Version
	}

	namespace := request.Namespace

	// Get chart path (optional for validation)
	chartPath := ""
	if request.ChartData != nil && strings.TrimSpace(*request.ChartData) != "" {
		// chartPath will be set later when processing chartData
	} else if utils.Config.DefaultAgentChartPath != "" {
		chartPath = utils.Config.DefaultAgentChartPath
	}
	// If no chart provided, validation still proceeds (just validates merged values)

	installNs, targetNs := resolveAgentInstallNamespace(namespace)

	// Build Helm deployment request
	deployReq := &agent_registry.HelmDeployRequest{
		ReleaseName:     request.HelmReleaseName,
		Namespace:       installNs,
		TargetNamespace: targetNs,
		ChartPath:       chartPath,
		ChartData:       request.ChartData,
		ChartVersion:    &request.HelmChartVersion,
		ValuesYAML:      request.ValuesYaml,
		Kubeconfig:      request.Kubeconfig,
		AgentID:         "temp-validation-id",
		ImageTag:        &version,
	}

	// Use Azure OpenAI credentials from the request (passed from UI)
	isMasked := func(val string) bool {
		return strings.HasPrefix(val, "***") || strings.Contains(val, "•")
	}
	if request.AzureOpenAIKey != nil && strings.TrimSpace(*request.AzureOpenAIKey) != "" && !isMasked(*request.AzureOpenAIKey) {
		deployReq.AzureOpenAIKey = request.AzureOpenAIKey
	} else if envVal := os.Getenv("AZURE_OPENAI_KEY"); envVal != "" {
		deployReq.AzureOpenAIKey = &envVal
	}
	if request.AzureOpenAIEndpoint != nil && strings.TrimSpace(*request.AzureOpenAIEndpoint) != "" {
		deployReq.AzureOpenAIEndpoint = request.AzureOpenAIEndpoint
	} else if envVal := os.Getenv("AZURE_OPENAI_ENDPOINT"); envVal != "" {
		deployReq.AzureOpenAIEndpoint = &envVal
	}
	if request.AzureOpenAIDeployment != nil && strings.TrimSpace(*request.AzureOpenAIDeployment) != "" {
		deployReq.AzureOpenAIDeployment = request.AzureOpenAIDeployment
	} else if envVal := os.Getenv("AZURE_OPENAI_DEPLOYMENT"); envVal != "" {
		deployReq.AzureOpenAIDeployment = &envVal
	}
	if request.AzureOpenAIAPIVersion != nil && strings.TrimSpace(*request.AzureOpenAIAPIVersion) != "" {
		deployReq.AzureOpenAIAPIVersion = request.AzureOpenAIAPIVersion
	} else if envVal := os.Getenv("AZURE_OPENAI_API_VERSION"); envVal != "" {
		deployReq.AzureOpenAIAPIVersion = &envVal
	}
	if request.AzureOpenAIEmbeddingDeployment != nil && strings.TrimSpace(*request.AzureOpenAIEmbeddingDeployment) != "" {
		deployReq.AzureOpenAIEmbeddingDeployment = request.AzureOpenAIEmbeddingDeployment
	} else if envVal := os.Getenv("AZURE_OPENAI_EMBEDDING_DEPLOYMENT"); envVal != "" {
		deployReq.AzureOpenAIEmbeddingDeployment = &envVal
	}

	// Use user-provided values YAML or empty if none
	finalValues := ""
	if request.ValuesYaml != nil && strings.TrimSpace(*request.ValuesYaml) != "" {
		finalValues = *request.ValuesYaml
	}

	// Return validation response with merged values
	return &model.HelmValidationResponse{
		Valid:        true,
		MergedValues: &finalValues,
		ReleaseName:  agent_registry.SanitizeReleaseName(request.HelmReleaseName),
		Namespace:    namespace,
	}, nil
}

// DeployAgentWithHelm is the resolver for the deployAgentWithHelm field.
func (r *mutationResolver) DeployAgentWithHelm(ctx context.Context, projectID string, request model.DeployAgentWithHelmRequest) (*model.DeployAgentWithHelmResponse, error) {
	// Create a RegisterAgentInput from the Helm deployment request
	version := "v1.0.0"
	if request.Version != nil {
		version = *request.Version
	}

	capabilities := []string{}
	if request.Capabilities != nil {
		capabilities = request.Capabilities
	}

	description := ""
	if request.Description != nil {
		description = *request.Description
	}

	// Validate Helm deployment parameters before registering agent
	chartPath := ""
	if request.ChartData == nil || *request.ChartData == "" {
		chartPath = utils.Config.DefaultAgentChartPath
		if chartPath == "" {
			return nil, fmt.Errorf("DEFAULT_AGENT_CHART_PATH is not configured and no chart data provided")
		}
	}

	// Build Helm deployment request for validation
	installNs, targetNs := resolveAgentInstallNamespace(request.Namespace)
	deployReq := &agent_registry.HelmDeployRequest{
		ReleaseName:     request.HelmReleaseName,
		Namespace:       installNs,
		TargetNamespace: targetNs,
		ChartPath:       chartPath,
		ChartData:       request.ChartData,
		ChartVersion:    &request.HelmChartVersion,
		ValuesYAML:      request.ValuesYaml,
		Kubeconfig:      request.Kubeconfig,
		AgentID:         "temp-validation-id", // Temporary for validation
		ImageTag:        request.Version,
	}

	// Use Azure OpenAI credentials from the request (passed from UI), fallback to backend env
	isMasked := func(val string) bool {
		return strings.HasPrefix(val, "***") || strings.Contains(val, "•")
	}
	if request.AzureOpenAIKey != nil && strings.TrimSpace(*request.AzureOpenAIKey) != "" && !isMasked(*request.AzureOpenAIKey) {
		deployReq.AzureOpenAIKey = request.AzureOpenAIKey
	} else if envVal := os.Getenv("AZURE_OPENAI_KEY"); envVal != "" {
		deployReq.AzureOpenAIKey = &envVal
	}
	if request.AzureOpenAIEndpoint != nil && strings.TrimSpace(*request.AzureOpenAIEndpoint) != "" {
		deployReq.AzureOpenAIEndpoint = request.AzureOpenAIEndpoint
	} else if envVal := os.Getenv("AZURE_OPENAI_ENDPOINT"); envVal != "" {
		deployReq.AzureOpenAIEndpoint = &envVal
	}
	if request.AzureOpenAIDeployment != nil && strings.TrimSpace(*request.AzureOpenAIDeployment) != "" {
		deployReq.AzureOpenAIDeployment = request.AzureOpenAIDeployment
	} else if envVal := os.Getenv("AZURE_OPENAI_DEPLOYMENT"); envVal != "" {
		deployReq.AzureOpenAIDeployment = &envVal
	}
	if request.AzureOpenAIAPIVersion != nil && strings.TrimSpace(*request.AzureOpenAIAPIVersion) != "" {
		deployReq.AzureOpenAIAPIVersion = request.AzureOpenAIAPIVersion
	} else if envVal := os.Getenv("AZURE_OPENAI_API_VERSION"); envVal != "" {
		deployReq.AzureOpenAIAPIVersion = &envVal
	}
	if request.AzureOpenAIEmbeddingDeployment != nil && strings.TrimSpace(*request.AzureOpenAIEmbeddingDeployment) != "" {
		deployReq.AzureOpenAIEmbeddingDeployment = request.AzureOpenAIEmbeddingDeployment
	} else if envVal := os.Getenv("AZURE_OPENAI_EMBEDDING_DEPLOYMENT"); envVal != "" {
		deployReq.AzureOpenAIEmbeddingDeployment = &envVal
	}

	// Validate Helm deployment will succeed (dry-run) before registering
	// For now, we'll proceed with registration and rollback if deployment fails

	// Prepare HelmReleaseName pointer
	var helmReleaseNamePtr *string
	if request.HelmReleaseName != "" {
		helmReleaseNamePtr = &request.HelmReleaseName
	}

	// Create the agent registration input
	registerInput := model.RegisterAgentInput{
		ProjectID:       projectID,
		Name:            request.Name,
		Description:     &description,
		Version:         version,
		Vendor:          "helm-deployment",
		Capabilities:    capabilities,
		Namespace:       request.Namespace,
		HelmReleaseName: helmReleaseNamePtr,
		ContainerImage: &model.ContainerImageInput{
			Registry:   "docker.io",
			Repository: "litmus/agent",
			Tag:        version,
		},
	}

	// Register the agent via the service layer
	req, err := agent_registry.MapRegisterAgentInputToRequest(registerInput)
	if err != nil {
		return nil, err
	}

	agent, err := r.agentRegistryService.RegisterAgent(ctx, req)
	if err != nil {
		return nil, err
	}

	// Now attempt Helm deployment with the real agent ID
	deployReq.AgentID = agent.AgentID

	if _, deployErr := agent_registry.DeployWithHelm(ctx, deployReq); deployErr != nil {
		// Helm deployment failed - delete the agent we just registered (hard delete)
		_, deleteErr := r.agentRegistryService.DeleteAgent(ctx, agent.AgentID, true)
		if deleteErr != nil {
			// Log but don't fail - agent is registered but deployment failed
			fmt.Printf("Failed to cleanup agent after deployment failure: %v\n", deleteErr)
		}
		return nil, fmt.Errorf("helm deployment failed: %w", deployErr)
	}

	_ = r.agentRegistryService.SetAgentStatus(ctx, agent.AgentID, agent_registry.AgentStatusActive)

	// Build environment variables list for deployment config
	envVars := []*model.EnvVariable{}

	// Helper function to create bool pointer
	boolPtr := func(b bool) *bool { return &b }

	// Add namespace
	if request.Namespace != "" {
		envVars = append(envVars, &model.EnvVariable{
			Name:        "NAMESPACE",
			Value:       request.Namespace,
			IsSensitive: boolPtr(false),
		})
	}

	// Add image tag
	if request.Version != nil {
		envVars = append(envVars, &model.EnvVariable{
			Name:        "IMAGE_TAG",
			Value:       *request.Version,
			IsSensitive: boolPtr(false),
		})
	}

	// Add Azure OpenAI variables with masking for sensitive ones
	if deployReq.AzureOpenAIKey != nil && strings.TrimSpace(*deployReq.AzureOpenAIKey) != "" {
		maskedKey := "***" + (*deployReq.AzureOpenAIKey)[len(*deployReq.AzureOpenAIKey)-4:]
		envVars = append(envVars, &model.EnvVariable{
			Name:        "AZURE_OPENAI_KEY",
			Value:       maskedKey,
			IsSensitive: boolPtr(true),
		})
	}
	if deployReq.AzureOpenAIEndpoint != nil && strings.TrimSpace(*deployReq.AzureOpenAIEndpoint) != "" {
		envVars = append(envVars, &model.EnvVariable{
			Name:        "AZURE_OPENAI_ENDPOINT",
			Value:       *deployReq.AzureOpenAIEndpoint,
			IsSensitive: boolPtr(false),
		})
	}
	if deployReq.AzureOpenAIDeployment != nil && strings.TrimSpace(*deployReq.AzureOpenAIDeployment) != "" {
		envVars = append(envVars, &model.EnvVariable{
			Name:        "AZURE_OPENAI_DEPLOYMENT",
			Value:       *deployReq.AzureOpenAIDeployment,
			IsSensitive: boolPtr(false),
		})
	}
	if deployReq.AzureOpenAIAPIVersion != nil && strings.TrimSpace(*deployReq.AzureOpenAIAPIVersion) != "" {
		envVars = append(envVars, &model.EnvVariable{
			Name:        "AZURE_OPENAI_API_VERSION",
			Value:       *deployReq.AzureOpenAIAPIVersion,
			IsSensitive: boolPtr(false),
		})
	}
	if deployReq.AzureOpenAIEmbeddingDeployment != nil && strings.TrimSpace(*deployReq.AzureOpenAIEmbeddingDeployment) != "" {
		envVars = append(envVars, &model.EnvVariable{
			Name:        "AZURE_OPENAI_EMBEDDING_DEPLOYMENT",
			Value:       *deployReq.AzureOpenAIEmbeddingDeployment,
			IsSensitive: boolPtr(false),
		})
	}

	// Build deployment configuration
	now := time.Now()
	deployedAtStr := now.UTC().Format(time.RFC3339)
	deploymentConfig := &model.DeploymentConfig{
		Namespace:            request.Namespace,
		ReleaseName:          agent_registry.SanitizeReleaseName(request.HelmReleaseName),
		ChartPath:            &deployReq.ChartPath,
		ChartVersion:         &request.HelmChartVersion,
		EnvironmentVariables: envVars,
		DeployedAt:           &deployedAtStr,
	}

	// Return the deployment response with full configuration details
	return &model.DeployAgentWithHelmResponse{
		AgentID:          agent.AgentID,
		Name:             agent.Name,
		Status:           model.AgentStatusRegistered,
		HelmReleaseName:  &request.HelmReleaseName,
		HelmChartVersion: &request.HelmChartVersion,
		DeploymentConfig: deploymentConfig,
	}, nil
}

// UpdateAgent is the resolver for the updateAgent field.
func (r *mutationResolver) UpdateAgent(ctx context.Context, agentID string, input model.UpdateAgentInput) (*model.Agent, error) {
	// Convert GraphQL input to service request
	req, err := agent_registry.MapUpdateAgentInputToRequest(input)
	if err != nil {
		return nil, err
	}

	// Call service layer
	agent, err := r.agentRegistryService.UpdateAgent(ctx, agentID, req)
	if err != nil {
		return nil, err
	}

	// Convert service response to GraphQL model
	return agent_registry.MapAgentToModel(agent), nil
}

// DeleteAgent is the resolver for the deleteAgent field.
func (r *mutationResolver) DeleteAgent(ctx context.Context, agentID string, hardDelete *bool) (*model.DeleteAgentResponse, error) {
	// Default to soft delete if not specified
	isHardDelete := false
	if hardDelete != nil {
		isHardDelete = *hardDelete
	}

	// Call service layer
	response, err := r.agentRegistryService.DeleteAgent(ctx, agentID, isHardDelete)
	if err != nil {
		return nil, err
	}

	// Convert service response to GraphQL model
	return agent_registry.MapDeleteAgentResponseToModel(response), nil
}

// ValidateAgentHealth is the resolver for the validateAgentHealth field.
func (r *mutationResolver) ValidateAgentHealth(ctx context.Context, agentID string) (*model.AgentStatusResponse, error) {
	// Call service layer
	result, err := r.agentRegistryService.ValidateAgentHealth(ctx, agentID)
	if err != nil {
		return nil, err
	}

	// Convert service response to GraphQL model
	now := time.Now().Format(time.RFC3339)
	return &model.AgentStatusResponse{
		AgentID:       agentID,
		Status:        model.AgentStatusActive,
		Healthy:       result.Healthy,
		LastCheckedAt: &now,
	}, nil
}

// SyncAgentToLangfuse is the resolver for the syncAgentToLangfuse field.
func (r *mutationResolver) SyncAgentToLangfuse(ctx context.Context, agentID string) (*model.SyncResponse, error) {
	// Call service layer
	response, err := r.agentRegistryService.SyncAgentToLangfuse(ctx, agentID)
	if err != nil {
		return nil, err
	}

	// Convert service response to GraphQL model
	return agent_registry.MapSyncResponseToModel(response), nil
}

// ImportMCPTools is the resolver for the importMCPTools field.
func (r *mutationResolver) ImportMCPTools(ctx context.Context, serverURL string) (*model.MCPImportResult, error) {
	client := &http.Client{Timeout: 10 * time.Second}
	resp, err := client.Get(serverURL + "/tools")
	if err != nil {
		return &model.MCPImportResult{
			Tools:  []string{},
			Errors: []string{fmt.Sprintf("could not reach MCP server: %v", err)},
		}, nil
	}
	defer resp.Body.Close()

	var payload struct {
		Tools []struct {
			Name        string `json:"name"`
			Description string `json:"description"`
		} `json:"tools"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&payload); err != nil {
		return &model.MCPImportResult{
			Tools:  []string{},
			Errors: []string{fmt.Sprintf("failed to parse MCP response: %v", err)},
		}, nil
	}

	names := make([]string, 0, len(payload.Tools))
	for _, t := range payload.Tools {
		names = append(names, t.Name)
	}
	return &model.MCPImportResult{Tools: names, Errors: []string{}}, nil
}

// CreateModelConfig is the resolver for the createModelConfig field.
func (r *mutationResolver) CreateModelConfig(ctx context.Context, projectID string, input model.ModelConfigInput) (*model.ModelConfigResult, error) {
	req := model_library.CreateModelConfigRequest{
		Alias:    input.Alias,
		Provider: input.Provider,
		Model:    input.Model,
		BaseURL:  input.BaseURL,
		APIKey:   input.APIKey,
	}
	cfg, err := r.modelLibraryService.CreateModelConfig(ctx, projectID, req)
	if err != nil {
		return nil, err
	}
	return &model.ModelConfigResult{
		Config:  mapModelConfig(cfg),
		Message: "Model config created successfully",
	}, nil
}

// UpdateModelConfig is the resolver for the updateModelConfig field.
func (r *mutationResolver) UpdateModelConfig(ctx context.Context, projectID string, alias string, input model.ModelConfigInput) (*model.ModelConfig, error) {
	req := model_library.UpdateModelConfigRequest{
		Provider: input.Provider,
		Model:    input.Model,
		BaseURL:  input.BaseURL,
		APIKey:   input.APIKey,
	}
	cfg, err := r.modelLibraryService.UpdateModelConfig(ctx, projectID, alias, req)
	if err != nil {
		return nil, err
	}
	return mapModelConfig(cfg), nil
}

// DeleteModelConfig is the resolver for the deleteModelConfig field.
func (r *mutationResolver) DeleteModelConfig(ctx context.Context, projectID string, alias string) (bool, error) {
	if err := r.modelLibraryService.DeleteModelConfig(ctx, projectID, alias); err != nil {
		return false, err
	}
	return true, nil
}

// TestModelConfig is the resolver for the testModelConfig field.
func (r *mutationResolver) TestModelConfig(ctx context.Context, input model.ModelConfigInput) (*model.ModelConfigTestResult, error) {
	req := model_library.TestModelConfigRequest{
		Provider: input.Provider,
		Model:    input.Model,
		APIKey:   input.APIKey,
		BaseURL:  input.BaseURL,
	}
	result, err := r.modelLibraryService.TestModelConfig(ctx, req)
	if err != nil {
		return nil, err
	}
	return &model.ModelConfigTestResult{
		Success:      result.Success,
		LatencyMs:    result.LatencyMs,
		ErrorMessage: result.ErrorMessage,
	}, nil
}

// RotateModelConfigKey is the resolver for the rotateModelConfigKey field.
func (r *mutationResolver) RotateModelConfigKey(ctx context.Context, projectID string, alias string, newAPIKey string) (*model.ModelConfig, error) {
	cfg, err := r.modelLibraryService.RotateAPIKey(ctx, projectID, alias, newAPIKey)
	if err != nil {
		return nil, err
	}
	return mapModelConfig(cfg), nil
}

// GetAgent is the resolver for the getAgent field.
func (r *queryResolver) GetAgent(ctx context.Context, agentID string) (*model.Agent, error) {
	// Call service layer
	agent, err := r.agentRegistryService.GetAgent(ctx, agentID)
	if err != nil {
		return nil, err
	}

	// Convert service response to GraphQL model
	return agent_registry.MapAgentToModel(agent), nil
}

// ListAgents is the resolver for the listAgents field.
func (r *queryResolver) ListAgents(ctx context.Context, filter *model.ListAgentsFilter, pagination model.PaginationInput) (*model.AgentListResponse, error) {
	// Convert GraphQL inputs to service types
	serviceFilter := agent_registry.MapAgentFilterInputToFilter(filter)
	servicePagination := agent_registry.MapPaginationInputToPagination(pagination)

	// Call service layer
	response, err := r.agentRegistryService.ListAgents(ctx, serviceFilter, servicePagination)
	if err != nil {
		return nil, err
	}

	// Convert service response to GraphQL model
	return agent_registry.MapAgentListResponseToModel(response), nil
}

// GetAgentsByCapabilities is the resolver for the getAgentsByCapabilities field.
func (r *queryResolver) GetAgentsByCapabilities(ctx context.Context, projectID string, capabilities []string) ([]*model.Agent, error) {
	// Call service layer
	agents, err := r.agentRegistryService.GetAgentsByCapabilities(ctx, projectID, capabilities)
	if err != nil {
		return nil, err
	}

	// Convert service responses to GraphQL models
	gqlAgents := make([]*model.Agent, len(agents))
	for i, agent := range agents {
		gqlAgents[i] = agent_registry.MapAgentToModel(agent)
	}

	return gqlAgents, nil
}

// GetAgentStatus is the resolver for the getAgentStatus field.
func (r *queryResolver) GetAgentStatus(ctx context.Context, agentID string) (*model.AgentStatusResponse, error) {
	// Call service layer
	status, err := r.agentRegistryService.GetAgentStatus(ctx, agentID)
	if err != nil {
		return nil, err
	}

	// Convert service response to GraphQL model
	return agent_registry.MapAgentStatusResponseToModel(status), nil
}

// GetAgentCapabilitiesTaxonomy is the resolver for the getAgentCapabilitiesTaxonomy field.
func (r *queryResolver) GetAgentCapabilitiesTaxonomy(ctx context.Context) ([]*model.CapabilityDefinition, error) {
	// Call service layer
	capabilities, err := r.agentRegistryService.GetAgentCapabilitiesTaxonomy(ctx)
	if err != nil {
		return nil, err
	}

	// Convert service responses to GraphQL models
	return agent_registry.MapCapabilityDefinitionsToModel(capabilities), nil
}

// GetKubernetesNamespaces is the resolver for the getKubernetesNamespaces field.
func (r *queryResolver) GetKubernetesNamespaces(ctx context.Context) ([]string, error) {
	// Call service layer to get available namespaces
	namespaces, err := r.agentRegistryService.GetKubernetesNamespaces(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch Kubernetes namespaces: %w", err)
	}
	return namespaces, nil
}

// GetEnvironmentVariables resolver
func (r *queryResolver) GetEnvironmentVariables(ctx context.Context) ([]*model.EnvironmentVariable, error) {
	envVars := []*model.EnvironmentVariable{}

	// Helper to add env var if it exists
	addEnvVar := func(name string, isSensitive bool) {
		value := os.Getenv(name)
		if value != "" {
			envVars = append(envVars, &model.EnvironmentVariable{
				Name:        name,
				Value:       value,
				IsSensitive: &isSensitive,
			})
		}
	}

	// Add Azure OpenAI credentials
	addEnvVar("AZURE_OPENAI_KEY", true)
	addEnvVar("AZURE_OPENAI_ENDPOINT", false)
	addEnvVar("AZURE_OPENAI_DEPLOYMENT", false)
	addEnvVar("AZURE_OPENAI_API_VERSION", false)
	addEnvVar("AZURE_OPENAI_EMBEDDING_DEPLOYMENT", false)

	return envVars, nil
}

// GetAgentYaml is the resolver for the getAgentYAML field.
func (r *queryResolver) GetAgentYaml(ctx context.Context, projectID string, agentName string) (string, error) {
	agentDoc, err := r.agentRegistryService.GetAgentByName(ctx, projectID, agentName)
	if err != nil {
		return "", err
	}
	return agent_registry.GenerateAgentYAML(agentDoc)
}

// ListModelConfigs is the resolver for the listModelConfigs field.
func (r *queryResolver) ListModelConfigs(ctx context.Context, projectID string) ([]*model.ModelConfig, error) {
	configs, err := r.modelLibraryService.ListModelConfigs(ctx, projectID)
	if err != nil {
		return nil, err
	}
	result := make([]*model.ModelConfig, len(configs))
	for i, c := range configs {
		result[i] = mapModelConfig(c)
	}
	return result, nil
}

// GetModelConfig is the resolver for the getModelConfig field.
func (r *queryResolver) GetModelConfig(ctx context.Context, projectID string, alias string) (*model.ModelConfig, error) {
	cfg, err := r.modelLibraryService.GetModelConfig(ctx, projectID, alias)
	if err != nil {
		return nil, err
	}
	return mapModelConfig(cfg), nil
}

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//   - You have helper methods in this file. Move them out to keep these resolver files clean.
func mapModelConfig(cfg *model_library.ModelConfig) *model.ModelConfig {
	return &model.ModelConfig{
		Alias:       cfg.Alias,
		Provider:    cfg.Provider,
		Model:       cfg.Model,
		BaseURL:     cfg.BaseURL,
		SecretRef:   cfg.SecretRef,
		AgentsUsing: cfg.AgentsUsing,
		Status:      cfg.Status,
		LastTested:  cfg.LastTested,
	}
}
func resolveAgentInstallNamespace(userNamespace string) (string, string) {
	sysNs := strings.TrimSpace(os.Getenv("AGENT_INSTALL_NAMESPACE"))
	if sysNs == "" {
		return userNamespace, ""
	}
	return sysNs, userNamespace
}

var _ = uuid.New
