package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49


import (
	"context"

	"github.com/litmuschaos/litmus/chaoscenter/graphql/server/graph/model"
	"github.com/litmuschaos/litmus/chaoscenter/graphql/server/pkg/agent_registry"
)

// RegisterAgent is the resolver for the registerAgent field.
func (r *mutationResolver) RegisterAgent(ctx context.Context, input model.RegisterAgentInput) (*model.Agent, error) {
	// Convert GraphQL input to service request
	req, err := agent_registry.MapRegisterAgentInputToRequest(input)
	if err != nil {
		return nil, err
	}

	// Call service layer
	agent, err := r.agentRegistryService.RegisterAgent(ctx, req)
	if err != nil {
		return nil, err
	}

	// Convert service response to GraphQL model
	return agent_registry.MapAgentToModel(agent), nil
}

// UpdateAgent is the resolver for the updateAgent field.
func (r *mutationResolver) UpdateAgent(ctx context.Context, id string, input model.UpdateAgentInput) (*model.Agent, error) {
	// Convert GraphQL input to service request
	req, err := agent_registry.MapUpdateAgentInputToRequest(input)
	if err != nil {
		return nil, err
	}

	// Call service layer
	agent, err := r.agentRegistryService.UpdateAgent(ctx, id, req)
	if err != nil {
		return nil, err
	}

	// Convert service response to GraphQL model
	return agent_registry.MapAgentToModel(agent), nil
}

// DeleteAgent is the resolver for the deleteAgent field.
func (r *mutationResolver) DeleteAgent(ctx context.Context, id string, hardDelete *bool) (*model.DeleteAgentResponse, error) {
	// Default to soft delete if not specified
	isHardDelete := false
	if hardDelete != nil {
		isHardDelete = *hardDelete
	}

	// Call service layer
	response, err := r.agentRegistryService.DeleteAgent(ctx, id, isHardDelete)
	if err != nil {
		return nil, err
	}

	// Convert service response to GraphQL model
	return agent_registry.MapDeleteAgentResponseToModel(response), nil
}

// ValidateAgentHealth is the resolver for the validateAgentHealth field.
func (r *mutationResolver) ValidateAgentHealth(ctx context.Context, id string) (*model.HealthCheckResult, error) {
	   // Call service layer
	   result, err := r.agentRegistryService.ValidateAgentHealth(ctx, id)
	   if err != nil {
		   return nil, err
	   }

	   // Convert service response to GraphQL model
	   return agent_registry.MapHealthCheckResultToModel(result), nil
}

// SyncAgentToLangfuse is the resolver for the syncAgentToLangfuse field.
func (r *mutationResolver) SyncAgentToLangfuse(ctx context.Context, id string) (*model.SyncResponse, error) {
	   // Call service layer
	   response, err := r.agentRegistryService.SyncAgentToLangfuse(ctx, id)
	   if err != nil {
		   return nil, err
	   }

	   // Convert service response to GraphQL model
	   return agent_registry.MapSyncResponseToModel(response), nil
}

// GetAgent is the resolver for the getAgent field.
func (r *queryResolver) GetAgent(ctx context.Context, id string) (*model.Agent, error) {
	// Call service layer
	agent, err := r.agentRegistryService.GetAgent(ctx, id)
	if err != nil {
		return nil, err
	}

	// Convert service response to GraphQL model
	return agent_registry.MapAgentToModel(agent), nil
}

// ListAgents is the resolver for the listAgents field.
func (r *queryResolver) ListAgents(ctx context.Context, filter *model.ListAgentsFilter, pagination model.PaginationInput) (*model.AgentListResponse, error) {
	// Convert GraphQL inputs to service types
	serviceFilter := agent_registry.MapAgentFilterInputToFilter(filter)
	servicePagination := agent_registry.MapPaginationInputToPagination(pagination)

	// Call service layer
	response, err := r.agentRegistryService.ListAgents(ctx, serviceFilter, servicePagination)
	if err != nil {
		return nil, err
	}

	// Convert service response to GraphQL model
	return agent_registry.MapAgentListResponseToModel(response), nil
}

// GetAgentsByCapabilities is the resolver for the getAgentsByCapabilities field.
func (r *queryResolver) GetAgentsByCapabilities(ctx context.Context, projectID string, capabilities []string) ([]*model.Agent, error) {
	// Call service layer
	agents, err := r.agentRegistryService.GetAgentsByCapabilities(ctx, projectID, capabilities)
	if err != nil {
		return nil, err
	}

	// Convert service responses to GraphQL models
	gqlAgents := make([]*model.Agent, len(agents))
	for i, agent := range agents {
		gqlAgents[i] = agent_registry.MapAgentToModel(agent)
	}

	return gqlAgents, nil
}

// GetAgentStatus is the resolver for the getAgentStatus field.
func (r *queryResolver) GetAgentStatus(ctx context.Context, id string) (*model.AgentStatusResponse, error) {
	   // Call service layer
	   status, err := r.agentRegistryService.GetAgentStatus(ctx, id)
	   if err != nil {
		   return nil, err
	   }

	   // Convert service response to GraphQL model
	   return agent_registry.MapAgentStatusResponseToModel(status), nil
}

// GetAgentCapabilitiesTaxonomy is the resolver for the getAgentCapabilitiesTaxonomy field.
func (r *queryResolver) GetAgentCapabilitiesTaxonomy(ctx context.Context) ([]*model.CapabilityDefinition, error) {
	   // Call service layer
	   capabilities, err := r.agentRegistryService.GetAgentCapabilitiesTaxonomy(ctx)
	   if err != nil {
		   return nil, err
	   }

	   // Convert service responses to GraphQL models
	   return agent_registry.MapCapabilityDefinitionsToModel(capabilities), nil
}

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//   - You have helper methods in this file. Move them out to keep these resolver files clean.
func (r *queryResolver) ValidateAgentHealth(ctx context.Context, agentID string) (*model.HealthCheckResult, error) {
	// Call service layer
	result, err := r.agentRegistryService.ValidateAgentHealth(ctx, agentID)
	if err != nil {
		return nil, err
	}

	// Convert service response to GraphQL model
	return agent_registry.MapHealthCheckResultToModel(result), nil
}
func (r *queryResolver) GetCapabilitiesTaxonomy(ctx context.Context) ([]*model.CapabilityDefinition, error) {
	// Call service layer
	capabilities, err := r.agentRegistryService.GetAgentCapabilitiesTaxonomy(ctx)
	if err != nil {
		return nil, err
	}

	// Convert service responses to GraphQL models
	return agent_registry.MapCapabilityDefinitionsToModel(capabilities), nil
}
