package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"

	"github.com/litmuschaos/litmus/chaoscenter/graphql/server/graph/model"
	"github.com/litmuschaos/litmus/chaoscenter/graphql/server/pkg/certification"
)

// GenerateCertification is the resolver for the generateCertification field.
func (r *mutationResolver) GenerateCertification(ctx context.Context, projectID string, request model.CertificationGenerationRequest) (*model.CertificationGenerationResponse, error) {
	if r.certificationService == nil {
		return nil, fmt.Errorf("certification service not initialised")
	}

	expectedRuns := 1
	if request.ExpectedRuns != nil && *request.ExpectedRuns > 0 {
		expectedRuns = *request.ExpectedRuns
	}

	out, err := r.certificationService.StartCertificationGeneration(ctx, certification.StartInput{
		ProjectID:       projectID,
		AgentID:         request.AgentID,
		AgentName:       request.AgentName,
		ExperimentID:    request.ExperimentID,
		ExperimentRunID: request.ExperimentRunID,
		ExpectedRuns:    expectedRuns,
	})
	if err != nil {
		return nil, err
	}

	msg := out.Message
	return &model.CertificationGenerationResponse{
		Status:                      out.Status,
		ExperimentRunWorkflowStatus: out.ExperimentRunWorkflowStatus,
		Message:                     &msg,
	}, nil
}

// GetCertificationStatus is the resolver for the getCertificationStatus field.
func (r *queryResolver) GetCertificationStatus(ctx context.Context, projectID string, experimentID string) (*model.CertificationExperimentSummary, error) {
	if r.certificationService == nil {
		return nil, fmt.Errorf("certification service not initialised")
	}

	exp, ready, err := r.certificationService.GetExperimentSummary(ctx, projectID, experimentID)
	if err != nil {
		return nil, err
	}
	if exp == nil {
		return nil, nil
	}

	summary := &model.CertificationExperimentSummary{
		ProjectID:     exp.ProjectID,
		AgentID:       exp.AgentID,
		AgentName:     exp.AgentName,
		ExperimentID:  exp.ExperimentID,
		Status:        exp.Status,
		ExpectedRuns:  exp.ExpectedRuns,
		TotalRuns:     exp.RunCounts.Total,
		CompletedRuns: exp.RunCounts.Completed,
		FailedRuns:    exp.RunCounts.Failed,
		Ready:         ready,
	}

	if exp.LatestCertificate != nil {
		if exp.LatestCertificate.CertificationID != "" {
			id := exp.LatestCertificate.CertificationID
			summary.CertificationID = &id
		}
		if exp.LatestCertificate.GeneratedAt != nil {
			ts := exp.LatestCertificate.GeneratedAt.UTC().Format("2006-01-02T15:04:05Z07:00")
			summary.GeneratedAt = &ts
		}
	}

	return summary, nil
}
