package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"

	"github.com/litmuschaos/litmus/chaoscenter/graphql/server/graph/model"
	"github.com/litmuschaos/litmus/chaoscenter/graphql/server/pkg/authorization"
)

// CreateFaultStudio is the resolver for the createFaultStudio field.
func (r *mutationResolver) CreateFaultStudio(ctx context.Context, projectID string, request model.CreateFaultStudioRequest) (*model.FaultStudio, error) {
	if err := authorization.ValidateRole(ctx, projectID,
		authorization.MutationRbacRules[authorization.CreateFaultStudio],
		model.InvitationAccepted.String()); err != nil {
		return nil, err
	}

	return r.faultStudioService.CreateFaultStudio(ctx, projectID, request)
}

// UpdateFaultStudio is the resolver for the updateFaultStudio field.
func (r *mutationResolver) UpdateFaultStudio(ctx context.Context, projectID string, studioID string, request model.UpdateFaultStudioRequest) (*model.FaultStudio, error) {
	if err := authorization.ValidateRole(ctx, projectID,
		authorization.MutationRbacRules[authorization.UpdateFaultStudio],
		model.InvitationAccepted.String()); err != nil {
		return nil, err
	}

	return r.faultStudioService.UpdateFaultStudio(ctx, projectID, studioID, request)
}

// DeleteFaultStudio is the resolver for the deleteFaultStudio field.
func (r *mutationResolver) DeleteFaultStudio(ctx context.Context, projectID string, studioID string) (bool, error) {
	if err := authorization.ValidateRole(ctx, projectID,
		authorization.MutationRbacRules[authorization.DeleteFaultStudio],
		model.InvitationAccepted.String()); err != nil {
		return false, err
	}

	return r.faultStudioService.DeleteFaultStudio(ctx, projectID, studioID)
}

// ToggleFaultInStudio is the resolver for the toggleFaultInStudio field.
func (r *mutationResolver) ToggleFaultInStudio(ctx context.Context, projectID string, studioID string, faultName string, enabled bool) (*model.ToggleFaultResponse, error) {
	if err := authorization.ValidateRole(ctx, projectID,
		authorization.MutationRbacRules[authorization.UpdateFaultStudio],
		model.InvitationAccepted.String()); err != nil {
		return nil, err
	}

	return r.faultStudioService.ToggleFaultInStudio(ctx, projectID, studioID, faultName, enabled)
}

// SetFaultStudioActive is the resolver for the setFaultStudioActive field.
func (r *mutationResolver) SetFaultStudioActive(ctx context.Context, projectID string, studioID string, isActive bool) (*model.FaultStudio, error) {
	if err := authorization.ValidateRole(ctx, projectID,
		authorization.MutationRbacRules[authorization.UpdateFaultStudio],
		model.InvitationAccepted.String()); err != nil {
		return nil, err
	}

	return r.faultStudioService.SetFaultStudioActive(ctx, projectID, studioID, isActive)
}

// AddFaultToStudio is the resolver for the addFaultToStudio field.
func (r *mutationResolver) AddFaultToStudio(ctx context.Context, projectID string, studioID string, fault model.FaultSelectionInput) (*model.FaultStudio, error) {
	if err := authorization.ValidateRole(ctx, projectID,
		authorization.MutationRbacRules[authorization.UpdateFaultStudio],
		model.InvitationAccepted.String()); err != nil {
		return nil, err
	}

	return r.faultStudioService.AddFaultToStudio(ctx, projectID, studioID, fault)
}

// RemoveFaultFromStudio is the resolver for the removeFaultFromStudio field.
func (r *mutationResolver) RemoveFaultFromStudio(ctx context.Context, projectID string, studioID string, faultName string) (*model.FaultStudio, error) {
	if err := authorization.ValidateRole(ctx, projectID,
		authorization.MutationRbacRules[authorization.UpdateFaultStudio],
		model.InvitationAccepted.String()); err != nil {
		return nil, err
	}

	return r.faultStudioService.RemoveFaultFromStudio(ctx, projectID, studioID, faultName)
}

// UpdateFaultInStudio is the resolver for the updateFaultInStudio field.
func (r *mutationResolver) UpdateFaultInStudio(ctx context.Context, projectID string, studioID string, faultName string, fault model.FaultSelectionInput) (*model.FaultStudio, error) {
	if err := authorization.ValidateRole(ctx, projectID,
		authorization.MutationRbacRules[authorization.UpdateFaultStudio],
		model.InvitationAccepted.String()); err != nil {
		return nil, err
	}

	return r.faultStudioService.UpdateFaultInStudio(ctx, projectID, studioID, fault)
}

// ListFaultStudios is the resolver for the listFaultStudios field.
func (r *queryResolver) ListFaultStudios(ctx context.Context, projectID string, request *model.ListFaultStudioRequest) (*model.ListFaultStudioResponse, error) {
	if err := authorization.ValidateRole(ctx, projectID,
		authorization.MutationRbacRules[authorization.ListFaultStudios],
		model.InvitationAccepted.String()); err != nil {
		return nil, err
	}

	return r.faultStudioService.ListFaultStudios(ctx, projectID, request)
}

// GetFaultStudio is the resolver for the getFaultStudio field.
func (r *queryResolver) GetFaultStudio(ctx context.Context, projectID string, studioID string) (*model.FaultStudio, error) {
	if err := authorization.ValidateRole(ctx, projectID,
		authorization.MutationRbacRules[authorization.GetFaultStudio],
		model.InvitationAccepted.String()); err != nil {
		return nil, err
	}

	return r.faultStudioService.GetFaultStudio(ctx, projectID, studioID)
}

// ListAvailableFaultsForStudio is the resolver for the listAvailableFaultsForStudio field.
func (r *queryResolver) ListAvailableFaultsForStudio(ctx context.Context, projectID string, hubID string) ([]*model.Chart, error) {
	if err := authorization.ValidateRole(ctx, projectID,
		authorization.MutationRbacRules[authorization.ListFaultStudios],
		model.InvitationAccepted.String()); err != nil {
		return nil, err
	}

	// Delegate to ChaosHub service to list faults for the specified hub
	return r.chaosHubService.ListChaosFaults(ctx, hubID, projectID)
}

// GetFaultStudioStats is the resolver for the getFaultStudioStats field.
func (r *queryResolver) GetFaultStudioStats(ctx context.Context, projectID string) (*model.FaultStudioStatsResponse, error) {
	if err := authorization.ValidateRole(ctx, projectID,
		authorization.MutationRbacRules[authorization.ListFaultStudios],
		model.InvitationAccepted.String()); err != nil {
		return nil, err
	}

	return r.faultStudioService.GetFaultStudioStats(ctx, projectID)
}

// IsFaultStudioNameAvailable is the resolver for the isFaultStudioNameAvailable field.
func (r *queryResolver) IsFaultStudioNameAvailable(ctx context.Context, projectID string, name string, excludeStudioID *string) (bool, error) {
	if err := authorization.ValidateRole(ctx, projectID,
		authorization.MutationRbacRules[authorization.ListFaultStudios],
		model.InvitationAccepted.String()); err != nil {
		return false, err
	}

	return r.faultStudioService.IsFaultStudioNameAvailable(ctx, projectID, name)
}
