package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"

	"github.com/litmuschaos/litmus/chaoscenter/graphql/server/graph/model"
	"github.com/litmuschaos/litmus/chaoscenter/graphql/server/pkg/fault_catalog"
)

// ListFaults is the resolver for the listFaults field.
func (r *queryResolver) ListFaults(ctx context.Context, scope *model.FaultScope, domain *string, targetApp *string) ([]*model.FaultSpec, error) {
	if r.faultCatalogService == nil {
		return []*model.FaultSpec{}, nil
	}
	var svcScope fault_catalog.FaultScope
	if scope != nil {
		svcScope = graphqlScopeToService(*scope)
	}
	var domainStr, targetAppStr string
	if domain != nil {
		domainStr = *domain
	}
	if targetApp != nil {
		targetAppStr = *targetApp
	}
	entries := r.faultCatalogService.ListFaults(svcScope, domainStr, targetAppStr)
	return faultEntriesToGraphQL(entries), nil
}

// GetFault is the resolver for the getFault field.
func (r *queryResolver) GetFault(ctx context.Context, name string) (*model.FaultSpec, error) {
	if r.faultCatalogService == nil {
		return nil, nil
	}
	entry, err := r.faultCatalogService.GetFault(name)
	if err != nil {
		if _, ok := err.(fault_catalog.ErrFaultNotFound); ok {
			return nil, nil
		}
		return nil, err
	}
	return faultEntryToGraphQL(entry), nil
}

// FaultsForApp is the resolver for the faultsForApp field.
func (r *queryResolver) FaultsForApp(ctx context.Context, appName string) ([]*model.FaultSpec, error) {
	if r.faultCatalogService == nil {
		return []*model.FaultSpec{}, nil
	}
	entries, err := r.faultCatalogService.FaultsForApp(ctx, appName)
	if err != nil {
		return nil, err
	}
	return faultEntriesToGraphQL(entries), nil
}
