package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"

	"github.com/litmuschaos/litmus/chaoscenter/graphql/server/graph/model"
	"github.com/litmuschaos/litmus/chaoscenter/graphql/server/pkg/authorization"
	"github.com/litmuschaos/litmus/chaoscenter/graphql/server/pkg/catalog"
)

// ListAgentHubCategories is the resolver for the listAgentHubCategories field.
func (r *queryResolver) ListAgentHubCategories(ctx context.Context, projectID string) ([]*model.AgentHubCategory, error) {
	err := authorization.ValidateRole(ctx, projectID,
		authorization.MutationRbacRules[authorization.ListCharts],
		model.InvitationAccepted.String())
	if err != nil {
		return nil, err
	}
	return r.agentHubService.ListAgentHubCategories(ctx, projectID)
}

// GetAgentHubStatus is the resolver for the getAgentHubStatus field.
func (r *queryResolver) GetAgentHubStatus(ctx context.Context, projectID string) (*model.AgentHubStatus, error) {
	err := authorization.ValidateRole(ctx, projectID,
		authorization.MutationRbacRules[authorization.ListCharts],
		model.InvitationAccepted.String())
	if err != nil {
		return nil, err
	}
	return r.agentHubService.GetAgentHubStatus(ctx, projectID)
}

// ListAppHubCategories is the resolver for the listAppHubCategories field.
func (r *queryResolver) ListAppHubCategories(ctx context.Context, projectID string) ([]*model.AppHubCategory, error) {
	err := authorization.ValidateRole(ctx, projectID,
		authorization.MutationRbacRules[authorization.ListCharts],
		model.InvitationAccepted.String())
	if err != nil {
		return nil, err
	}
	return r.appHubService.ListAppHubCategories(ctx, projectID)
}

// GetAppHubStatus is the resolver for the getAppHubStatus field.
func (r *queryResolver) GetAppHubStatus(ctx context.Context, projectID string) (*model.AppHubStatus, error) {
	err := authorization.ValidateRole(ctx, projectID,
		authorization.MutationRbacRules[authorization.ListCharts],
		model.InvitationAccepted.String())
	if err != nil {
		return nil, err
	}
	return r.appHubService.GetAppHubStatus(ctx, projectID)
}

// ListApplications is the resolver for the listApplications field.
func (r *queryResolver) ListApplications(ctx context.Context, projectID string) ([]*model.ApplicationSpec, error) {
	if r.catalogService == nil {
		return []*model.ApplicationSpec{}, nil
	}
	entries, err := r.catalogService.ListApplications(ctx, projectID)
	if err != nil {
		return nil, err
	}
	result := make([]*model.ApplicationSpec, 0, len(entries))
	for _, e := range entries {
		result = append(result, catalog.ToGraphQLModel(e))
	}
	return result, nil
}

// GetApplication is the resolver for the getApplication field.
func (r *queryResolver) GetApplication(ctx context.Context, projectID string, appName string) (*model.ApplicationSpec, error) {
	if r.catalogService == nil {
		return nil, nil
	}
	e, err := r.catalogService.GetApplication(ctx, projectID, appName)
	if err != nil {
		return nil, err
	}
	return catalog.ToGraphQLModel(e), nil
}
