---
apiVersion: litmuschaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  name: network-loss
  version: 0.1.0
  annotations:
    categories: Network
    vendor: LitmusChaos
spec:
  displayName: Network Loss
  categoryDescription: |
    Network loss fault injects network packet loss on the target pods in a Kubernetes cluster.
    - Causes network packet loss on the outgoing traffic of a pod by injecting packet loss using traffic control (tc) and iptables.
    - The applications deployed on the pods may experience connection timeouts and retransmission in the scenarios of high packet loss.
    - Tests application resiliency and recovery workflows under high-packet-loss network conditions.
  keywords:
    - Kubernetes
    - Network
    - Packet Loss
    - Chaos
  platforms:
    - GKE
    - Konvoy
    - Packet(Kubeadm)
    - Minikube
    - EKS
    - AKS
    - Kind
    - Rancher
    - OpenShift(OKD)
  maintainers:
    - name: LitmusChaos
      email: support@litmuschaos.io
  experiments:
    - network-loss
  minKubeVersion: 1.12.0
  labels:
    app.kubernetes.io/component: chartserviceversion
    app.kubernetes.io/version: ci
  links:
    - name: Documentation
      url: https://litmuschaos.github.io/litmus/experiments/categories/contents
  icon:
    - url: /faults/network/icons/network-loss.svg
      mediatype: "image/svg+xml"

