---
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: http-5xx-abort-chaos
  namespace: default
spec:
  appinfo:
    appns: ''
    applabel: ''
    appkind: ''
  # It can be active/stop
  engineState: 'active'
  chaosServiceAccount: http-5xx-abort-sa
  experiments:
    - name: http-5xx-abort
      spec:
        components:
          env:
            # set chaos duration (in sec) as desired
            - name: TOTAL_CHAOS_DURATION
              value: '60'

            # HTTP status code to inject
            - name: HTTP_STATUS_CODE
              value: '500'

            # Percentage of requests to fail
            - name: PERCENTAGE_ABORT
              value: '50'

            ## percentage of total pods to target
            - name: PODS_AFFECTED_PERC
              value: ''
