---
apiVersion: litmuschaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  name: db-pod-kill
  version: 0.1.0
  annotations:
    categories: Database
    vendor: LitmusChaos
spec:
  displayName: DB Pod Kill
  categoryDescription: |
    DB pod kill fault disrupts the state of database resources in Kubernetes. This fault injects random pod delete failures against specified database application.
    - Causes (forced/graceful) pod failure of random replicas of a database deployment
    - Tests database replica availability, failover mechanisms, and recovery workflows
  keywords:
    - Kubernetes
    - Database
    - Pod
    - Chaos
  platforms:
    - GKE
    - Konvoy
    - Packet(Kubeadm)
    - Minikube
    - EKS
    - AKS
    - Kind
    - Rancher
    - OpenShift(OKD)
  maintainers:
    - name: LitmusChaos
      email: support@litmuschaos.io
  experiments:
    - db-pod-kill
  minKubeVersion: 1.12.0
  labels:
    app.kubernetes.io/component: chartserviceversion
    app.kubernetes.io/version: ci
  links:
    - name: Documentation
      url: https://litmuschaos.github.io/litmus/experiments/categories/contents
  icon:
    - url: /faults/database/icons/db-pod-kill.svg
      mediatype: "image/svg+xml"
