"""
Metrics extraction module for IT-Ops Agent run reports.
Extracts quantitative and qualitative metrics from agent run log files using LLMs.
"""

import asyncio
import json
import re
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from data_models.metrics_model import (
    LLMQualitativeExtraction,
    LLMQuantitativeExtraction,
    MetricsExtractionResult,
)
from utils.azure_openai_util import AzureLLMClient
from utils.load_config import ConfigLoader
from utils.mongodb_util import MongoDBClient, MongoDBConfig
from utils.setup_logging import logger


class MetricsExtractor:
    """
    Extracts metrics from IT-Ops agent run report files.

    This class parses the log files generated by IT-Ops agents during
    fault detection and mitigation runs, extracting both quantitative
    and qualitative metrics.
    """

    # Regex patterns for extraction
    PATTERNS = {
        "session_id": r"Session ID:\s*([a-f0-9\-]+)",
        "namespace": r"Namespace\s+(\S+)\s+already exists|namespace:\s*(\S+)",
        "deployment": r"NAME:\s*(\S+)",
        "helm_deploy_time": r"LAST DEPLOYED:\s*(.+)",
        "fault_injection": r"Misconfig fault for service:\s*(\S+)\s*\|\s*namespace:\s*(\S+)",
        "fault_service": r"Service:\s*(\S+)\s*\|\s*Namespace:\s*(\S+)",
        "agent_action": r"\[32mAgent:\s*\[0m```markdown\s*([\s\S]*?)```",
        "service_response": r"\[34mService:\s*\[0m([\s\S]*?)(?=\[32mAgent:|INFO:|$)",
        "ttd": r"'TTD':\s*([\d.]+)",
        "steps": r"'steps':\s*(\d+)",
        "in_tokens": r"'in_tokens':\s*(\d+)",
        "out_tokens": r"'out_tokens':\s*(\d+)",
        "detection_accuracy": r"'Detection Accuracy':\s*'(\w+)'",
        "correct_detection": r"Correct detection:\s*(\w+)",
        "reasoning_score": r"'reasoning_score':\s*(\d+)",
        "reasoning_judgement": r"'reasoning_judgement':\s*'([\s\S]*?)'(?=,\s*'reasoning_score')",
        "submission_status": r"SubmissionStatus\.(\w+)",
        "framework_overhead": r"Framework overhead:\s*([\d.]+)",
        "http_request": r"HTTP Request:\s*POST\s*(\S+)",
        "tool_call": r"```markdown\s*([\w_]+)\((.*?)\)\s*```",
        "error_message": r"\[error\]:\s*(.+)",
        "connection_refused": r"Connection refused",
        "pods_ready_time": r"\[(\d{2}:\d{2}:\d{2})\].*All pods.*are ready",
        "start_time": r"\[(\d{2}:\d{2}:\d{2})\].*Waiting for all pods",
    }

    def __init__(self, file_path: str):
        """
        Initialize the extractor with a file path.

        Args:
            file_path: Path to the agent run report file.
        """
        self.file_path = Path(file_path)
        self.content: str = ""
        self.errors: List[str] = []
        self.warnings: List[str] = []

    def load_file(self) -> bool:
        """Load the file content."""
        try:
            with open(self.file_path, "r", encoding="utf-8") as f:
                self.content = f.read()
            return True
        except FileNotFoundError:
            self.errors.append(f"File not found: {self.file_path}")
            return False
        except Exception as e:
            self.errors.append(f"Error reading file: {str(e)}")
            return False

    # ==================== LLM-BASED EXTRACTION METHODS ====================

    QUANTITATIVE_PROMPT = """You are an expert IT Operations analyst. Extract quantitative metrics from this IT-Ops agent run report.

Extract the following fields (use null/None for missing values):

1. **Session Info**:
   - session_id: Session ID (UUID format)
   - namespace: Kubernetes namespace
   - deployment_name: Deployment/application name

2. **Time Metrics**:
   - fault_injection_time: Timestamp or time (in seconds) when fault was injected
   - agent_fault_detection_time: Timestamp when the agent detected the fault
   - agent_fault_mitigation_time: Timestamp when the agent mitigated the fault
   - framework_overhead_seconds: Framework overhead in seconds

3. **Fault Info**:
   - fault_detected: Type of fault detected by the agent (e.g., "Misconfig", "Network Issue", etc.)
   - fault_type: Type of fault injected (e.g., "Misconfig")
   - fault_target_service: Service where fault was injected
   - fault_namespace: Namespace of the faulty service

4. **Trajectory Metrics**:
   - trajectory_steps: Number of steps in the agent trajectory
   - input_tokens: Total number of input tokens used
   - output_tokens: Total number of output tokens used

5. **Tool Calls**: List all agent tool calls with:
   - tool_name (or name): Name of the tool (get_logs, get_metrics, exec_shell, submit, etc.)
   - arguments (or args): Dict of arguments passed to the tool
   - was_successful (or success): Boolean indicating if the call succeeded
   - response_summary: Brief summary of the response (optional)
   - timestamp: Timestamp of the call (optional)

Look for patterns like:
- "Session ID: <uuid>"
- "'TTD': <number>" or "Time to Detection: <number>"
- "'steps': <number>", "'in_tokens': <number>", "'out_tokens': <number>"
- "'Detection Accuracy': 'Correct'" or "Correct detection: Yes"
- "SubmissionStatus.VALID_SUBMISSION"
- "Misconfig fault for service: <service> | namespace: <ns>"
- "Framework overhead: <number>"
- Timestamps like [HH:MM:SS] or datetime strings
- Agent tool calls in format: tool_name(arg1, arg2)

Return a JSON object with all extracted metrics. Ensure tool_calls is a list of dicts with the specified fields."""

    QUALITATIVE_PROMPT = """You are an expert IT Operations analyst evaluating an IT-Ops agent's performance quality.

Evaluate and extract the following fields:

1. **RAI Check** (Responsible AI):
   - rai_check_status: 'Passed', 'Failed', or 'Not Evaluated'
   - rai_check_notes: Notes on RAI compliance (check for harmful, biased, or inappropriate content)

2. **Trajectory Efficiency**:
   - trajectory_efficiency_score: Score from 0-10 (Were steps logical and efficient? Score based on: optimal path, minimal redundancy, logical progression)
   - trajectory_efficiency_notes: Detailed efficiency assessment

3. **Security Compliance**:
   - security_compliance_status: 'Compliant', 'Non-Compliant', 'Partially Compliant', or 'Not Evaluated'
   - security_compliance_notes: Notes on security compliance (check for exposed credentials, sensitive data)

4. **Acceptance Criteria**:
   - acceptance_criteria_met: Boolean - Was anomaly correctly detected? Was root cause identified?
   - acceptance_criteria_notes: Detailed evaluation of acceptance criteria

5. **Response Quality**:
   - response_quality_score: Score from 0-10 (Quality of reasoning and explanations, clarity and accuracy of conclusions)
   - response_quality_notes: Detailed response quality assessment

6. **Reasoning** (from report if available):
   - reasoning_judgement: Overall reasoning judgement (extract if present in report)
   - reasoning_score: Reasoning score from 0-10 (extract if present in report)

7. **Known Limitations**:
   - known_limitations: List of observed limitations (what could have been done better?)

8. **Recommendations**:
   - recommendations: List of actionable improvements

9. **Agent Summary**:
   - agent_summary: A concise summary of the agent's actions, findings, and remediation steps taken

Return a JSON object with all qualitative assessments. Ensure all list fields (known_limitations, recommendations) are arrays of strings."""

    def _iter_content_chunks(self, chunk_size: int = 80000) -> List[str]:
        """Yield content in fixed-size chunks without truncating the file."""
        if not self.content:
            return []

        chunks = [
            self.content[max(i - 100, 0) : i + chunk_size]
            for i in range(0, len(self.content), chunk_size)
        ]
        if len(chunks) > 1:
            self.warnings.append(
                f"Content split into {len(chunks)} chunks of ~{chunk_size} chars"
            )
        return chunks

    @staticmethod
    def _merge_tool_calls(
        base_calls: List[Dict[str, Any]],
        new_calls: List[Dict[str, Any]],
    ) -> List[Dict[str, Any]]:
        """Merge tool calls while avoiding obvious duplicates."""
        merged = list(base_calls)
        seen = set()
        for call in merged:
            try:
                seen.add(json.dumps(call, sort_keys=True))
            except TypeError:
                seen.add(str(call))

        for call in new_calls:
            try:
                key = json.dumps(call, sort_keys=True)
            except TypeError:
                key = str(call)
            if key not in seen:
                merged.append(call)
                seen.add(key)
        return merged

    @staticmethod
    def _merge_text(base: Optional[str], new: Optional[str]) -> Optional[str]:
        """Merge text fields by appending new content if it differs."""
        if not new:
            return base
        if not base:
            return new
        if new in base:
            return base
        return f"{base}\n{new}"

    def _merge_quantitative(
        self,
        base: LLMQuantitativeExtraction,
        new: LLMQuantitativeExtraction,
    ) -> LLMQuantitativeExtraction:
        """Merge quantitative extraction results, preferring non-default values."""
        if base is None:
            return new
        if new is None:
            return base

        base.session_id = base.session_id or new.session_id
        base.namespace = base.namespace or new.namespace
        base.deployment_name = base.deployment_name or new.deployment_name
        base.fault_injection_time = (
            base.fault_injection_time or new.fault_injection_time
        )
        base.agent_fault_detection_time = (
            base.agent_fault_detection_time or new.agent_fault_detection_time
        )
        base.agent_fault_mitigation_time = (
            base.agent_fault_mitigation_time or new.agent_fault_mitigation_time
        )
        if base.framework_overhead_seconds is None:
            base.framework_overhead_seconds = new.framework_overhead_seconds

        if base.fault_detected in (None, "", "Unknown"):
            if new.fault_detected not in (None, "", "Unknown"):
                base.fault_detected = new.fault_detected

        base.trajectory_steps = max(
            base.trajectory_steps or 0, new.trajectory_steps or 0
        )
        base.input_tokens = max(base.input_tokens or 0, new.input_tokens or 0)
        base.output_tokens = max(base.output_tokens or 0, new.output_tokens or 0)

        base.fault_type = base.fault_type or new.fault_type
        base.fault_target_service = (
            base.fault_target_service or new.fault_target_service
        )
        base.fault_namespace = base.fault_namespace or new.fault_namespace

        base.tool_calls = self._merge_tool_calls(base.tool_calls, new.tool_calls)
        return base

    def _merge_qualitative(
        self,
        base: LLMQualitativeExtraction,
        new: LLMQualitativeExtraction,
    ) -> LLMQualitativeExtraction:
        """Merge qualitative extraction results, preferring non-default values."""
        if base is None:
            return new
        if new is None:
            return base

        if base.rai_check_status in (None, "", "Not Evaluated"):
            if new.rai_check_status not in (None, "", "Not Evaluated"):
                base.rai_check_status = new.rai_check_status
        base.rai_check_notes = self._merge_text(
            base.rai_check_notes, new.rai_check_notes
        )

        if base.trajectory_efficiency_score is None:
            base.trajectory_efficiency_score = new.trajectory_efficiency_score
        base.trajectory_efficiency_notes = self._merge_text(
            base.trajectory_efficiency_notes, new.trajectory_efficiency_notes
        )

        if base.security_compliance_status in (None, "", "Not Evaluated"):
            if new.security_compliance_status not in (None, "", "Not Evaluated"):
                base.security_compliance_status = new.security_compliance_status
        base.security_compliance_notes = self._merge_text(
            base.security_compliance_notes, new.security_compliance_notes
        )

        if base.acceptance_criteria_met is None:
            base.acceptance_criteria_met = new.acceptance_criteria_met
        elif (
            base.acceptance_criteria_met is False
            and new.acceptance_criteria_met is True
        ):
            base.acceptance_criteria_met = True
        base.acceptance_criteria_notes = self._merge_text(
            base.acceptance_criteria_notes, new.acceptance_criteria_notes
        )

        if base.response_quality_score is None:
            base.response_quality_score = new.response_quality_score
        base.response_quality_notes = self._merge_text(
            base.response_quality_notes, new.response_quality_notes
        )

        base.reasoning_judgement = self._merge_text(
            base.reasoning_judgement, new.reasoning_judgement
        )
        if base.reasoning_score is None:
            base.reasoning_score = new.reasoning_score
        elif new.reasoning_score is not None:
            base.reasoning_score = max(base.reasoning_score, new.reasoning_score)

        if new.known_limitations:
            base.known_limitations = list(
                dict.fromkeys(base.known_limitations + new.known_limitations)
            )
        if new.recommendations:
            base.recommendations = list(
                dict.fromkeys(base.recommendations + new.recommendations)
            )

        base.agent_summary = (
            self._merge_text(base.agent_summary, new.agent_summary) or ""
        )
        return base

    async def extract_quantitative_with_llm(
        self, llm_client: AzureLLMClient
    ) -> LLMQuantitativeExtraction:
        """Use LLM to extract quantitative metrics."""
        chunks = self._iter_content_chunks()
        if not chunks:
            return LLMQuantitativeExtraction()

        merged = LLMQuantitativeExtraction()
        total = len(chunks)
        for index, chunk in enumerate(chunks, start=1):
            try:
                response, _ = await llm_client.with_structured_output(
                    model_name="quantitative_extractor",
                    messages=[
                        {
                            "role": "user",
                            "content": f"Chunk {index} of {total}:\n{chunk}",
                        }
                    ],
                    output_format=LLMQuantitativeExtraction,
                    system_prompt=self.QUANTITATIVE_PROMPT,
                    max_tokens=10000,
                )

                if isinstance(response, LLMQuantitativeExtraction):
                    merged = self._merge_quantitative(merged, response)
                elif isinstance(response, dict):
                    merged = self._merge_quantitative(
                        merged, LLMQuantitativeExtraction.model_validate(response)
                    )
            except Exception as e:
                logger.error(f"LLM quantitative extraction failed (chunk {index}): {e}")
                self.warnings.append(
                    f"LLM quantitative extraction error (chunk {index}): {str(e)}"
                )

        return merged

    async def extract_qualitative_with_llm(
        self, llm_client: AzureLLMClient
    ) -> LLMQualitativeExtraction:
        """Use LLM to extract qualitative metrics."""
        chunks = self._iter_content_chunks()
        if not chunks:
            return LLMQualitativeExtraction()

        merged = LLMQualitativeExtraction()
        total = len(chunks)
        for index, chunk in enumerate(chunks, start=1):
            try:
                response, _ = await llm_client.with_structured_output(
                    model_name="qualitative_extractor",
                    messages=[
                        {
                            "role": "user",
                            "content": f"Chunk {index} of {total}:\n{chunk}",
                        }
                    ],
                    output_format=LLMQualitativeExtraction,
                    system_prompt=self.QUALITATIVE_PROMPT,
                    max_tokens=10000,
                )

                if isinstance(response, LLMQualitativeExtraction):
                    merged = self._merge_qualitative(merged, response)
                elif isinstance(response, dict):
                    merged = self._merge_qualitative(
                        merged, LLMQualitativeExtraction.model_validate(response)
                    )
            except Exception as e:
                logger.error(f"LLM qualitative extraction failed (chunk {index}): {e}")
                self.warnings.append(
                    f"LLM qualitative extraction error (chunk {index}): {str(e)}"
                )

        return merged

    async def extract_with_llm(self, llm_client: Optional[AzureLLMClient] = None):
        """
        Extract metrics using LLM.

        Args:
            llm_client: Optional AzureLLMClient. If not provided, creates a new one.

        Returns:
            MetricsExtractionResult containing the extracted metrics.
        """
        if not self.load_file():
            return MetricsExtractionResult(success=False, errors=self.errors)

        owns_client = llm_client is None
        if owns_client:
            llm_client = AzureLLMClient()

        try:
            # Extract quantitative and qualitative metrics in parallel
            quant_result, qual_result = await asyncio.gather(
                self.extract_quantitative_with_llm(llm_client),
                self.extract_qualitative_with_llm(llm_client),
                return_exceptions=True,
            )

            # Handle exceptions
            if isinstance(quant_result, Exception):
                logger.error(f"Quantitative extraction failed: {quant_result}")
                self.warnings.append(f"Quantitative extraction error: {quant_result}")
                quant_result = LLMQuantitativeExtraction()

            if isinstance(qual_result, Exception):
                logger.error(f"Qualitative extraction failed: {qual_result}")
                self.warnings.append(f"Qualitative extraction error: {qual_result}")
                qual_result = LLMQualitativeExtraction()

            # Convert to final metrics
            metrics = {
                "quantitative_metrics": quant_result.model_dump(),
                "qualitative_metrics": qual_result.model_dump(),
            }

            # Persist LLM metrics to MongoDB
            await self._save_llm_metrics_to_mongodb(quant_result, qual_result)

            return MetricsExtractionResult(
                success=True, metrics=metrics, warnings=self.warnings
            )

        except Exception as e:
            self.errors.append(f"LLM extraction error: {str(e)}")
            logger.error(f"LLM extraction error: {e}")
            return MetricsExtractionResult(
                success=False, errors=self.errors, warnings=self.warnings
            )
        finally:
            if owns_client and llm_client:
                await llm_client.close()

    async def _save_llm_metrics_to_mongodb(
        self,
        quantitative: LLMQuantitativeExtraction,
        qualitative: LLMQualitativeExtraction,
    ) -> None:
        """Persist LLM-extracted metrics to MongoDB."""
        try:
            config = MongoDBConfig(ConfigLoader.load_config())
            client = MongoDBClient(config)
            client.initialize_collections()
        except Exception as e:
            warning = f"MongoDB config/client initialization failed: {e}"
            logger.warning(warning)
            self.warnings.append(warning)
            return

        try:
            await client.insert_metrics_async(
                quantitative=quantitative,
                qualitative=qualitative,
                session_id=quantitative.session_id,
                metadata={
                    "run_file_path": str(self.file_path),
                    "extraction_method": "llm",
                },
            )
        except Exception as e:
            warning = f"MongoDB insert failed: {e}"
            logger.warning(warning)
            self.warnings.append(warning)
        finally:
            await client.close_async()


def extract_metrics_from_file(file_path: str) -> MetricsExtractionResult:
    """
    Convenience function to extract metrics from a file.

    Args:
        file_path: Path to the agent run report file.

    Returns:
        MetricsExtractionResult containing the extracted metrics.
    """
    extractor = MetricsExtractor(file_path)
    return extractor.extract()


def extract_metrics_from_multiple_files(
    file_paths: List[str],
) -> List[MetricsExtractionResult]:
    """
    Extract metrics from multiple files.

    Args:
        file_paths: List of paths to agent run report files.

    Returns:
        List of MetricsExtractionResult objects.
    """
    results = []
    for file_path in file_paths:
        result = extract_metrics_from_file(file_path)
        results.append(result)
    return results


# ==================== LLM-BASED EXTRACTION FUNCTIONS ====================


async def extract_metrics_with_llm(
    file_path: str, llm_client: Optional[AzureLLMClient] = None
):
    """
    Extract metrics from a file using LLM (recommended).

    Args:
        file_path: Path to the agent run report file.
        llm_client: Optional shared LLM client.

    Returns:
        MetricsExtractionResult containing the extracted metrics.
    """
    extractor = MetricsExtractor(file_path)
    return await extractor.extract_with_llm(llm_client)


async def extract_metrics_from_multiple_files_with_llm(
    file_paths: List[str],
) -> List[MetricsExtractionResult]:
    """
    Extract metrics from multiple files using LLM.

    Args:
        file_paths: List of paths to agent run report files.

    Returns:
        List of MetricsExtractionResult objects.
    """
    llm_client = AzureLLMClient()
    try:
        results = []
        for file_path in file_paths:
            result = await extract_metrics_with_llm(file_path, llm_client)
            results.append(result)
        return results
    finally:
        await llm_client.close()


if __name__ == "__main__":
    import sys

    async def main():
        # Example usage
        if len(sys.argv) > 1:
            file_path = sys.argv[1]
        else:
            # Default to pid_run_1.txt for testing
            file_path = "agentcert/data/pid_run_1.txt"

        print("=" * 70)
        print("LLM-BASED METRICS EXTRACTION")
        print("=" * 70)
        print(f"\nExtracting metrics from: {file_path}")
        print("Using Azure OpenAI for intelligent extraction...\n")

        result = await extract_metrics_with_llm(file_path)

        print("✅ Metrics extraction successful!\n")
        print("Extracted Metrics:")
        print(result.model_dump_json(indent=2))

    asyncio.run(main())
