---
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: config-misconfig-chaos
  namespace: default
spec:
  appinfo:
    appns: ''
    applabel: ''
    appkind: ''
  # It can be active/stop
  engineState: 'active'
  chaosServiceAccount: config-misconfig-sa
  experiments:
    - name: config-misconfig
      spec:
        components:
          env:
            # set chaos duration (in sec) as desired
            - name: TOTAL_CHAOS_DURATION
              value: '60'

            # Config key to corrupt
            - name: CONFIG_KEY
              value: ''

            # Config value to set
            - name: CONFIG_VALUE
              value: ''

            ## percentage of total pods to target
            - name: PODS_AFFECTED_PERC
              value: ''
