apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: infra-cluster-role
rules:
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["clusterroles", "clusterrolebindings", "roles", "rolebindings"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
