---
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: rbac-revoke-chaos
  namespace: default
spec:
  appinfo:
    appns: ''
    applabel: ''
    appkind: ''
  # It can be active/stop
  engineState: 'active'
  chaosServiceAccount: rbac-revoke-sa
  experiments:
    - name: rbac-revoke
      spec:
        components:
          env:
            # set chaos duration (in sec) as desired
            - name: TOTAL_CHAOS_DURATION
              value: '60'

            # Service account to revoke permissions
            - name: SERVICE_ACCOUNT
              value: ''

            ## percentage of total pods to target
            - name: PODS_AFFECTED_PERC
              value: ''
